"""pricing_structure_consumer_price_store_margin_distrib_rate

Revision ID: 7e44b6dfb0dd
Revises: 195966681e56
Create Date: 2026-05-17 15:02:23.973419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e44b6dfb0dd'
down_revision: Union[str, None] = '195966681e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('distribution_rate_pct', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('products', sa.Column('consumer_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('store_margin_pct', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'store_margin_pct')
    op.drop_column('products', 'consumer_price')
    op.drop_column('clients', 'distribution_rate_pct')
    # ### end Alembic commands ###
