"""phase3_movements

Revision ID: d6bb58002806
Revises: 6a3b5546742f
Create Date: 2026-05-17 06:51:02.728164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bb58002806'
down_revision: Union[str, None] = '6a3b5546742f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_boxes', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=20), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_movement_date'), 'movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_movements_movement_type'), 'movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_movements_product_id'), 'movements', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movements_product_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_type'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_date'), table_name='movements')
    op.drop_table('movements')
    # ### end Alembic commands ###
